import { JetBrains_Mono, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//components
import Header from "../components/Header.jsx";
import PageTransition from "../components/PageTransition";
import StairTransition from "../components/StairTransition";
import CustomCursor from "../components/CustomCursor.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 700, 800],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainsMono.variable} antialiased`}
      >
        <CustomCursor/>
        <Header/>
        <StairTransition/>
        <PageTransition>
        {children}
        </PageTransition> 
        
      </body>
    </html>
  );
}
